- hosts: 127.0.0.1
  become: yes

  tasks:

  - name: Add Zabbix repository
    yum: name=https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm state=present

  - name: Install Zabbix-Agent
    yum: name=zabbix-agent state=present

  - service: name=zabbix-agent state=started

  - service: name=zabbix-agent enabled=yes

  - name: Delete config file
    command: rm -f /etc/zabbix/zabbix_agentd.conf

  - name: Copy agent conf
    template:
      src: /home/centos/zabbix_agentd.conf
      dest: /etc/zabbix/
      mode: 0755

  - name: Restart zabbix agent
    service: name=zabbix-agent state=restarted

